# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
gems: [jekyll-paginate]
theme:
  # Meta
  title: Boss2bmj
  avatar: boss.png
  avatar2: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <p>Welcome to Boss's World.This is my blog that will contain about my life such as my family, my favorite hobby, my major that i study in university, and so on. Here is the best place to introduce myself to everyone!!.</p>

     <p>Nice to Meet you all. If you want to know me more, Please go below and choose the topic that you want to know about me.</p>
  header_text_feature_image:

  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "boss2bmj@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: https://www.facebook.com/peranat.lappakobkit
  flickr:
  github: "rohanchandra/type-theme"
  google_plus:
  instagram: boss2bmj
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:
  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
